2021-06-30 14:06:29,460 INFO    Thread-7  :26494 [wandb_setup.py:_flush():69] setting env: {'project': 'MLN_sweep_cifar10_asymmetric_0.4', 'entity': 'jeongeun', 'root_dir': '/home/jeongeun/MLN_XRobust', 'run_id': 'x6rb7b0i', 'sweep_param_path': '/home/jeongeun/MLN_XRobust/wandb/sweep-kdi9ph10/config-x6rb7b0i.yaml', 'sweep_id': 'kdi9ph10'}
2021-06-30 14:06:29,460 INFO    Thread-7  :26494 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-30 14:06:29,461 INFO    Thread-7  :26494 [wandb_init.py:_log_setup():337] Logging user logs to /home/jeongeun/MLN_XRobust/wandb/run-20210630_140629-x6rb7b0i/logs/debug.log
2021-06-30 14:06:29,461 INFO    Thread-7  :26494 [wandb_init.py:_log_setup():338] Logging internal logs to /home/jeongeun/MLN_XRobust/wandb/run-20210630_140629-x6rb7b0i/logs/debug-internal.log
2021-06-30 14:06:29,461 INFO    Thread-7  :26494 [wandb_init.py:init():370] calling init triggers
2021-06-30 14:06:29,461 INFO    Thread-7  :26494 [wandb_init.py:init():375] wandb.init called with sweep_config: {'ratio1': 0, 'ratio2': 1}
config: {'k': 24, 'sig_min': 1, 'sig_max': 10, 'lr': 5e-05, 'wd': 5e-05, 'lr_rate': 0.2}
2021-06-30 14:06:29,461 INFO    Thread-7  :26494 [wandb_init.py:init():419] starting backend
2021-06-30 14:06:29,461 INFO    Thread-7  :26494 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-06-30 14:06:29,464 INFO    Thread-7  :26494 [backend.py:ensure_launched():135] starting backend process...
2021-06-30 14:06:29,521 INFO    Thread-7  :26494 [backend.py:ensure_launched():139] started backend process with pid: 12498
2021-06-30 14:06:29,522 INFO    Thread-7  :26494 [wandb_init.py:init():424] backend started and connected
2021-06-30 14:06:29,524 INFO    Thread-7  :26494 [wandb_run.py:_config_callback():873] config_cb None None {'ratio1': 0, 'ratio2': 1}
2021-06-30 14:06:29,526 INFO    Thread-7  :26494 [wandb_init.py:init():472] updated telemetry
2021-06-30 14:06:29,526 INFO    Thread-7  :26494 [wandb_init.py:init():491] communicating current version
2021-06-30 14:06:30,329 INFO    Thread-7  :26494 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.10.33 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-06-30 14:06:30,329 INFO    Thread-7  :26494 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-06-30 14:06:30,535 INFO    Thread-7  :26494 [wandb_init.py:init():529] starting run threads in backend
2021-06-30 14:06:30,612 INFO    Thread-7  :26494 [wandb_run.py:_console_start():1624] atexit reg
2021-06-30 14:06:30,613 INFO    Thread-7  :26494 [wandb_run.py:_redirect():1498] redirect: SettingsConsole.REDIRECT
2021-06-30 14:06:30,613 INFO    Thread-7  :26494 [wandb_run.py:_redirect():1503] Redirecting console.
2021-06-30 14:06:30,613 ERROR   Thread-7  :26494 [wandb_run.py:_redirect():1562] Failed to redirect.
Traceback (most recent call last):
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1555, in _redirect
    out_redir.install()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/jeongeun/.pyenv/versions/3.8.8/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-06-30 14:06:30,613 INFO    Thread-7  :26494 [wandb_init.py:init():554] run started, returning control to user process
2021-06-30 14:06:30,614 INFO    Thread-7  :26494 [wandb_watch.py:watch():40] Watching
2021-06-30 15:50:32,984 INFO    MainThread:26494 [wandb_run.py:_atexit_cleanup():1594] got exitcode: 0
2021-06-30 15:50:32,991 INFO    MainThread:26494 [wandb_run.py:_restore():1566] restore
