2021-07-12 01:08:23,514 INFO    Thread-2  :93342 [wandb_setup.py:_flush():69] setting env: {'project': 'MLN_sweep_mnist_symmetric_0.5', 'entity': 'jeongeun', 'root_dir': '/home/jeongeun/MLN_XRobust', 'sweep_id': '95lllol3', 'run_id': '5zdbwjw8', 'sweep_param_path': '/home/jeongeun/MLN_XRobust/wandb/sweep-95lllol3/config-5zdbwjw8.yaml'}
2021-07-12 01:08:23,514 INFO    Thread-2  :93342 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-12 01:08:23,514 INFO    Thread-2  :93342 [wandb_init.py:_log_setup():337] Logging user logs to /home/jeongeun/MLN_XRobust/wandb/run-20210712_010823-5zdbwjw8/logs/debug.log
2021-07-12 01:08:23,514 INFO    Thread-2  :93342 [wandb_init.py:_log_setup():338] Logging internal logs to /home/jeongeun/MLN_XRobust/wandb/run-20210712_010823-5zdbwjw8/logs/debug-internal.log
2021-07-12 01:08:23,515 INFO    Thread-2  :93342 [wandb_init.py:init():370] calling init triggers
2021-07-12 01:08:23,515 INFO    Thread-2  :93342 [wandb_init.py:init():375] wandb.init called with sweep_config: {'ratio1': 0.1, 'ratio2': 0.1}
config: {'k': 10, 'sig_min': 1, 'sig_max': 10, 'lr': 0.001, 'wd': 0.0001, 'lr_rate': 0.05}
2021-07-12 01:08:23,515 INFO    Thread-2  :93342 [wandb_init.py:init():419] starting backend
2021-07-12 01:08:23,515 INFO    Thread-2  :93342 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-12 01:08:23,569 INFO    Thread-2  :93342 [backend.py:ensure_launched():135] starting backend process...
2021-07-12 01:08:23,636 INFO    Thread-2  :93342 [backend.py:ensure_launched():139] started backend process with pid: 93518
2021-07-12 01:08:23,640 INFO    Thread-2  :93342 [wandb_init.py:init():424] backend started and connected
2021-07-12 01:08:23,647 INFO    Thread-2  :93342 [wandb_run.py:_config_callback():873] config_cb None None {'ratio1': 0.1, 'ratio2': 0.1}
2021-07-12 01:08:23,649 INFO    Thread-2  :93342 [wandb_init.py:init():472] updated telemetry
2021-07-12 01:08:23,650 INFO    Thread-2  :93342 [wandb_init.py:init():491] communicating current version
2021-07-12 01:08:24,473 INFO    Thread-2  :93342 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.10.33 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-07-12 01:08:24,474 INFO    Thread-2  :93342 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-12 01:08:24,694 ERROR   Thread-2  :93342 [wandb_init.py:init():783] error
Traceback (most recent call last):
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 757, in init
    run = wi.init()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 505, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 667, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 655, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 545, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/jeongeun/.pyenv/versions/3.8.8/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/jeongeun/.pyenv/versions/3.8.8/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
