2021-07-15 00:39:26,860 INFO    Thread-27 :33855 [wandb_setup.py:_flush():69] setting env: {'project': 'MLN_sweep_cifar10_symmetric_0.2', 'entity': 'jeongeun', 'root_dir': '/home/jeongeun/MLN_XRobust', 'run_id': 'fe5ev9pb', 'sweep_param_path': '/home/jeongeun/MLN_XRobust/wandb/sweep-3kwpb21f/config-fe5ev9pb.yaml', 'sweep_id': '3kwpb21f'}
2021-07-15 00:39:26,860 INFO    Thread-27 :33855 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-15 00:39:26,860 INFO    Thread-27 :33855 [wandb_init.py:_log_setup():337] Logging user logs to /home/jeongeun/MLN_XRobust/wandb/run-20210715_003926-fe5ev9pb/logs/debug.log
2021-07-15 00:39:26,860 INFO    Thread-27 :33855 [wandb_init.py:_log_setup():338] Logging internal logs to /home/jeongeun/MLN_XRobust/wandb/run-20210715_003926-fe5ev9pb/logs/debug-internal.log
2021-07-15 00:39:26,861 INFO    Thread-27 :33855 [wandb_init.py:init():370] calling init triggers
2021-07-15 00:39:26,861 INFO    Thread-27 :33855 [wandb_init.py:init():375] wandb.init called with sweep_config: {'ratio1': 0, 'ratio2': 1}
config: {'k': 24, 'sig_min': 1, 'sig_max': 10, 'lr': 0.0001, 'wd': 0.0005, 'lr_rate': 0.2}
2021-07-15 00:39:26,861 INFO    Thread-27 :33855 [wandb_init.py:init():419] starting backend
2021-07-15 00:39:26,861 INFO    Thread-27 :33855 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-15 00:39:26,864 INFO    Thread-27 :33855 [backend.py:ensure_launched():135] starting backend process...
2021-07-15 00:39:26,916 INFO    Thread-27 :33855 [backend.py:ensure_launched():139] started backend process with pid: 125156
2021-07-15 00:39:26,917 INFO    Thread-27 :33855 [wandb_init.py:init():424] backend started and connected
2021-07-15 00:39:26,919 INFO    Thread-27 :33855 [wandb_run.py:_config_callback():873] config_cb None None {'ratio1': 0, 'ratio2': 1}
2021-07-15 00:39:26,921 INFO    Thread-27 :33855 [wandb_init.py:init():472] updated telemetry
2021-07-15 00:39:26,921 INFO    Thread-27 :33855 [wandb_init.py:init():491] communicating current version
2021-07-15 00:39:27,735 INFO    Thread-27 :33855 [wandb_init.py:init():496] got version response upgrade_message: "wandb version 0.10.33 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-07-15 00:39:27,736 INFO    Thread-27 :33855 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-15 00:39:27,957 INFO    Thread-27 :33855 [wandb_init.py:init():529] starting run threads in backend
2021-07-15 00:39:28,041 INFO    Thread-27 :33855 [wandb_run.py:_console_start():1624] atexit reg
2021-07-15 00:39:28,042 INFO    Thread-27 :33855 [wandb_run.py:_redirect():1498] redirect: SettingsConsole.REDIRECT
2021-07-15 00:39:28,042 INFO    Thread-27 :33855 [wandb_run.py:_redirect():1503] Redirecting console.
2021-07-15 00:39:28,042 ERROR   Thread-27 :33855 [wandb_run.py:_redirect():1562] Failed to redirect.
Traceback (most recent call last):
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1555, in _redirect
    out_redir.install()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/jeongeun/.pyenv/versions/ue/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/jeongeun/.pyenv/versions/3.8.8/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-07-15 00:39:28,042 INFO    Thread-27 :33855 [wandb_init.py:init():554] run started, returning control to user process
2021-07-15 00:39:28,043 INFO    Thread-27 :33855 [wandb_watch.py:watch():40] Watching
2021-07-15 01:14:58,368 ERROR   Thread-1  :33855 [internal_api.py:execute():130] 502 response executing GraphQL.
2021-07-15 01:14:58,369 ERROR   Thread-1  :33855 [internal_api.py:execute():131] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2021-07-15 03:41:05,563 INFO    Thread-27 :33855 [wandb_run.py:finish():1294] finishing run jeongeun/MLN_sweep_cifar10_symmetric_0.2/fe5ev9pb
